---
- name: Fonts-Nerd | Create fonts directory
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/fonts"
    state: directory
    mode: "0755"

- name: Fonts-Nerd | Install Fonts
  vars:
    files_to_download:
      - url: "https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFontMono-Regular.ttf"
        dest: "{{ xdg_data_home }}/fonts/UbuntuMonoNerdFontMono-Regular.ttf"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: yes  # Forces download even if the file already exists
  loop: "{{ files_to_download }}"
  notify:
    - update font cache

- name: Fonts-Nerd | Register Default Profile
  ansible.builtin.command: gsettings get org.gnome.Terminal.ProfilesList default
  register: default_profile

- name: Fonts-Nerd | Set Font for Default Profile
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ default_profile.stdout }}/ font "UbuntuMono Nerd Font Mono 14"

- name: Fonts-Nerd | Disable System Font for Default Profile
  ansible.builtin.command: gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ default_profile.stdout }}/ use-system-font false