---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  roles:
    - { role: system, tags: ['system']}
    - { role: bash, tags: ['bash'] }
    - { role: catppuccin-gnome }
    - { role: fonts-nerd }
    - { role: lsd }
    - { role: tldr }
    - { role: nala, tags: ['nala']}
    - { role: vscode, tags: ['vscode']}
    - { role: tmux, tags: ['tmux']}
    - { role: lazyvim, tags: ['lazyvim']}
    # - { role: neovim, tags: ['neovim']}

  # tasks:
  #   - name: Set roles
  #     ansible.builtin.set_fact:
  #       run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
  #     tags:
  #       - always

  #   - name: Display roles
  #     ansible.builtin.debug:
  #       var: run_roles
  #     tags:
  #       - always

  #   - name: Run roles
  #     ansible.builtin.include_role:
  #       apply:
  #         tags:
  #           - "{{ roles_item }}"
  #       name: "{{ roles_item }}"
  #     loop_control:
  #       loop_var: roles_item
  #     with_items: "{{ run_roles }}"
  #     tags:
  #       - always
