---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  # roles:
  #   - { role: system, tags: ['system'] }
  #   - { role: bash, tags: ['bash'] }
  #   - { role: catppuccin-gnome, tags: ['theme'] }
  #   - { role: fonts-nerd, tags: ['fonts'] }
  #   - { role: lsd, tags: ['lsd'] }
  #   - { role: nala, tags: ['nala'] }

  roles:
    - { role: system, tags: ['always'] }
    - { role: bash, tags: ['always', 'bash'] }
    - { role: catppuccin-gnome, tags: ['always'] }
    - { role: fonts-nerd, tags: ['always'] }
    - { role: lsd, tags: ['always'] }
    - { role: nala }

  # tasks:
  #   - name: Set roles
  #     ansible.builtin.set_fact:
  #       run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
  #     tags:
  #       - always

  #   - name: Display roles
  #     ansible.builtin.debug:
  #       var: run_roles
  #     tags:
  #       - always

  #   - name: Run roles
  #     ansible.builtin.include_role:
  #       apply:
  #         tags:
  #           - "{{ roles_item }}"
  #       name: "{{ roles_item }}"
  #     loop_control:
  #       loop_var: roles_item
  #     with_items: "{{ run_roles }}"
  #     tags:
  #       - always
