---
- name: "System | {{ ansible_distribution }} | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | {{ ansible_distribution }} | Install Packages"
  ansible.builtin.apt:
    name:
      - jq
      - curl
    state: present
  become: true

- name: "System | {{ ansible_distribution }} | Prefer Dark Theme"
  ansible.builtin.command: gsettings set org.gnome.shell.ubuntu color-scheme prefer-dark

