---
- name: "Git | Run Tasks: {{ ansible_distribution }}" # TODO: Convert all roles to use ansible_distribution
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install Packages
  import_tasks: packages.yml
